name = "habits-social-staging"
main = ".output/server/index.mjs"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "habits-social-live"
routes = [
  { pattern = "habitssocial.com", custom_domain = true },
  { pattern = "www.habitssocial.com", custom_domain = true }
]

[env.production.vars]
# Production environment variables (public)
NODE_ENV = "production"
NUXT_PUBLIC_REALTIME_ENABLED = "false"
NUXT_PUBLIC_PARTYKIT_HOST = "habits-social-realtime-production.ieatcode4breakfast.partykit.dev"

[[kv_namespaces]]
binding = "AUTH_KV"
id = "da1a5af94cbc47acbda4f1b214b1b134"

[[kv_namespaces]]
binding = "CHAT_KV"
id = "be61e29f25db41d0ad1480cd1a27c8f8"

[[env.production.kv_namespaces]]
binding = "AUTH_KV"
id = "4a137eebd4fc44c1b123385a64c242c9"

[[env.production.kv_namespaces]]
binding = "CHAT_KV"
id = "4faf1845d9464f8fa9720164d5a9203a"

[assets]
directory = ".output/public"
binding = "ASSETS"

[observability.logs]
enabled = true
invocation_logs = true

[vars]
NUXT_PUBLIC_REALTIME_ENABLED = "true"
NUXT_PUBLIC_PARTYKIT_HOST = "habits-social-realtime-staging.ieatcode4breakfast.partykit.dev"
# DATABASE_URL = "your_connection_string_here"
# Note: For production, use 'wrangler secret put DATABASE_URL' instead.
